apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
  - name: ssh
    port: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ee:latest
        envFrom:
        - configMapRef:
            name: gitlab
        ports:
        - containerPort: 80
        - containerPort: 22
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
      volumes:
      - name: gitlab-config
        hostPath:
          path: /srv/gitlab/config
          type: Directory
      - name: gitlab-logs
        hostPath:
          path: /srv/gitlab/logs
          type: Directory
      - name: gitlab-data
        hostPath:
          path: /srv/gitlab/data
          type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab
data:
  GITLAB_OMNIBUS_CONFIG: "external_url 'http://example.com/';"
