apiVersion: v1
kind: Service
metadata:
  name: h5ai
spec:
  selector:
    app: h5ai
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h5ai
  labels:
    app: h5ai
spec:
  selector:
    matchLabels:
      app: h5ai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: h5ai
    spec:
      containers:
      - name: h5ai
        image: php:apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: h5ai-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: h5ai-persistent-storage
        hostPath:
          path: /srv/h5ai
          type: Directory